version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-action-dependencies:
        patterns:
          - "*"
