name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Dependency Review
        uses: actions/dependency-review-action@v4.5.0
